import type { Stokvel, User, DashboardActivity } from "./types";

export const MOCK_USER: User = {
  id: "u1",
  email: "thabo@yieldly.demo",
  name: "Thabo Mokoena",
  phone: "+27 82 123 4567",
  idNumber: "000101 1234 087",
  address: "123 Luthuli Street, Berea, Johannesburg, 2198",
  employmentStatus: "Employed full-time",
  incomeRange: "R 10 000 – R 20 000",
  goal: "home",
  duration: 24,
  riskAppetite: "moderate",
  monthlyContribution: 1500,
  cardLast4: "4242",
  bankName: "FNB",
  kycStatus: "verified",
  onboardingComplete: true,
};

export const MOCK_STOKVELS: Stokvel[] = [
  {
    id: "s1",
    name: "Thembisa Home Builders",
    description: "A community of future homeowners pooling resources for property deposits and bond repayments.",
    goal: "home",
    duration: 24,
    monthlyContribution: 1500,
    maxMembers: 12,
    currentMembers: 8,
    riskAppetite: "moderate",
    privacy: "public",
    createdAt: "2024-01-15",
    members: [
      { id: "u1", name: "Thabo M.", role: "admin", contributionStatus: "paid" },
      { id: "u2", name: "Sizwe K.", role: "member", contributionStatus: "paid" },
      { id: "u3", name: "Lerato N.", role: "member", contributionStatus: "paid" },
      { id: "u4", name: "Nomsa D.", role: "member", contributionStatus: "pending" },
      { id: "u5", name: "Jabu S.", role: "member", contributionStatus: "paid" },
      { id: "u6", name: "Kgosi P.", role: "member", contributionStatus: "paid" },
      { id: "u7", name: "Thembi R.", role: "member", contributionStatus: "pending" },
      { id: "u8", name: "Bongani T.", role: "pending", contributionStatus: "pending" },
    ],
    milestones: [
      { title: "Stokvel created", date: "Jan 2024", completed: true },
      { title: "5 members joined", date: "Feb 2024", completed: true },
      { title: "First contribution cycle", date: "Feb 2024", completed: true },
      { title: "50% of goal reached", date: "Aug 2024", completed: false },
      { title: "Goal reached", date: "Jan 2026", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 12000, memberCount: 8 },
      { month: "January 2025", amount: 12000, memberCount: 8 },
      { month: "December 2024", amount: 10500, memberCount: 7 },
      { month: "November 2024", amount: 10500, memberCount: 7 },
      { month: "October 2024", amount: 9000, memberCount: 6 },
    ],
    activities: [
      { id: "a1", type: "contribution", text: "Monthly contribution of R 12 000 collected", timestamp: "2 hours ago" },
      { id: "a2", type: "member_joined", text: "Bongani T. requested to join", timestamp: "5 hours ago" },
      { id: "a3", type: "milestone", text: "Reached R 96 000 total contributions", timestamp: "1 day ago" },
    ],
  },
  {
    id: "s2",
    name: "Luthuli Street Entrepreneurs",
    description: "Pooling capital to launch and scale small businesses in our community.",
    goal: "business",
    duration: 36,
    monthlyContribution: 2000,
    maxMembers: 10,
    currentMembers: 5,
    riskAppetite: "aggressive",
    privacy: "public",
    createdAt: "2023-12-01",
    members: [
      { id: "u1", name: "Thabo M.", role: "member", contributionStatus: "paid" },
      { id: "u9", name: "Sizwe K.", role: "admin", contributionStatus: "paid" },
      { id: "u10", name: "Lerato N.", role: "member", contributionStatus: "paid" },
      { id: "u11", name: "Nomsa D.", role: "member", contributionStatus: "pending" },
      { id: "u12", name: "Jabu S.", role: "member", contributionStatus: "paid" },
    ],
    milestones: [
      { title: "Stokvel created", date: "Dec 2023", completed: true },
      { title: "3 members joined", date: "Jan 2024", completed: true },
      { title: "First contribution cycle", date: "Jan 2024", completed: true },
      { title: "Business plan submitted", date: "Jun 2024", completed: false },
      { title: "Capital distribution", date: "Dec 2026", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 10000, memberCount: 5 },
      { month: "January 2025", amount: 10000, memberCount: 5 },
      { month: "December 2024", amount: 10000, memberCount: 5 },
    ],
    activities: [
      { id: "a4", type: "contribution", text: "Monthly contribution of R 10 000 collected", timestamp: "2 hours ago" },
      { id: "a5", type: "member_joined", text: "Jabu S. joined the stokvel", timestamp: "1 week ago" },
    ],
  },
  {
    id: "s3",
    name: "Maboneng Education Fund",
    description: "Saving for tuition, textbooks, and skills courses for ourselves and our children.",
    goal: "education",
    duration: 12,
    monthlyContribution: 800,
    maxMembers: 10,
    currentMembers: 10,
    riskAppetite: "conservative",
    privacy: "public",
    createdAt: "2024-08-01",
    members: Array.from({ length: 10 }, (_, i) => ({
      id: `edu-${i}`,
      name: ["Thabo M.", "Sizwe K.", "Lerato N.", "Nomsa D.", "Jabu S.", "Kgosi P.", "Thembi R.", "Bongani T.", "Zanele M.", "David K."][i],
      role: i === 0 ? "admin" : "member",
      contributionStatus: i < 7 ? "paid" : "pending",
    })),
    milestones: [
      { title: "Stokvel created", date: "Aug 2024", completed: true },
      { title: "10 members joined", date: "Aug 2024", completed: true },
      { title: "First contribution cycle", date: "Sep 2024", completed: true },
      { title: "50% of goal reached", date: "Jan 2025", completed: true },
      { title: "Goal reached", date: "Aug 2025", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 8000, memberCount: 10 },
      { month: "January 2025", amount: 8000, memberCount: 10 },
      { month: "December 2024", amount: 8000, memberCount: 10 },
      { month: "November 2024", amount: 8000, memberCount: 10 },
      { month: "October 2024", amount: 8000, memberCount: 10 },
    ],
    activities: [
      { id: "a6", type: "milestone", text: "Reached 50% of savings goal (R 4 800)", timestamp: "1 day ago" },
      { id: "a7", type: "contribution", text: "Monthly contribution of R 8 000 collected", timestamp: "2 days ago" },
    ],
  },
  {
    id: "s4",
    name: "Soweto Business Circle",
    description: "Supporting business launches and expansions in the Soweto community.",
    goal: "business",
    duration: 24,
    monthlyContribution: 1200,
    maxMembers: 10,
    currentMembers: 7,
    riskAppetite: "moderate",
    privacy: "public",
    createdAt: "2024-06-01",
    members: Array.from({ length: 7 }, (_, i) => ({
      id: `sow-${i}`,
      name: ["Thabo M.", "Sizwe K.", "Lerato N.", "Nomsa D.", "Jabu S.", "Kgosi P.", "Thembi R."][i],
      role: i === 1 ? "admin" : "member",
      contributionStatus: i < 5 ? "paid" : "pending",
    })),
    milestones: [
      { title: "Stokvel created", date: "Jun 2024", completed: true },
      { title: "5 members joined", date: "Jul 2024", completed: true },
      { title: "First contribution cycle", date: "Jul 2024", completed: true },
      { title: "Business plan review", date: "Dec 2024", completed: false },
      { title: "Capital distribution", date: "Jun 2026", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 8400, memberCount: 7 },
      { month: "January 2025", amount: 8400, memberCount: 7 },
    ],
    activities: [
      { id: "a8", type: "contribution", text: "Monthly contribution of R 8 400 collected", timestamp: "2 hours ago" },
    ],
  },
  {
    id: "s5",
    name: "Cape Town Travel Tribe",
    description: "Saving for dream trips and travel experiences together.",
    goal: "travel",
    duration: 12,
    monthlyContribution: 2500,
    maxMembers: 8,
    currentMembers: 4,
    riskAppetite: "aggressive",
    privacy: "invite-only",
    createdAt: "2025-01-01",
    members: Array.from({ length: 4 }, (_, i) => ({
      id: `ctt-${i}`,
      name: ["Thabo M.", "Sizwe K.", "Lerato N.", "Nomsa D."][i],
      role: i === 2 ? "admin" : "member",
      contributionStatus: "paid",
    })),
    milestones: [
      { title: "Stokvel created", date: "Jan 2025", completed: true },
      { title: "4 members joined", date: "Feb 2025", completed: true },
      { title: "First contribution cycle", date: "Feb 2025", completed: true },
      { title: "50% of goal reached", date: "Jul 2025", completed: false },
      { title: "Goal reached", date: "Jan 2026", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 10000, memberCount: 4 },
    ],
    activities: [
      { id: "a9", type: "contribution", text: "Monthly contribution of R 10 000 collected", timestamp: "1 day ago" },
    ],
  },
  {
    id: "s6",
    name: "Durban Emergency Pool",
    description: "Building a safety net for unexpected expenses and emergencies.",
    goal: "emergency",
    duration: 6,
    monthlyContribution: 500,
    maxMembers: 6,
    currentMembers: 6,
    riskAppetite: "conservative",
    privacy: "public",
    createdAt: "2024-09-01",
    members: Array.from({ length: 6 }, (_, i) => ({
      id: `dep-${i}`,
      name: ["Thabo M.", "Sizwe K.", "Lerato N.", "Nomsa D.", "Jabu S.", "Kgosi P."][i],
      role: i === 3 ? "admin" : "member",
      contributionStatus: "paid",
    })),
    milestones: [
      { title: "Stokvel created", date: "Sep 2024", completed: true },
      { title: "6 members joined", date: "Sep 2024", completed: true },
      { title: "First contribution cycle", date: "Oct 2024", completed: true },
      { title: "Goal reached", date: "Mar 2025", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 3000, memberCount: 6 },
      { month: "January 2025", amount: 3000, memberCount: 6 },
    ],
    activities: [
      { id: "a10", type: "contribution", text: "Monthly contribution of R 3 000 collected", timestamp: "2 hours ago" },
    ],
  },
  {
    id: "s7",
    name: "Johannesburg Youth Fund",
    description: "Empowering young people through education and skills development.",
    goal: "education",
    duration: 36,
    monthlyContribution: 1000,
    maxMembers: 15,
    currentMembers: 3,
    riskAppetite: "moderate",
    privacy: "public",
    createdAt: "2025-01-15",
    members: [
      { id: "u1", name: "Thabo M.", role: "member", contributionStatus: "paid" },
      { id: "jyf-1", name: "Sizwe K.", role: "admin", contributionStatus: "paid" },
      { id: "jyf-2", name: "Lerato N.", role: "member", contributionStatus: "pending" },
    ],
    milestones: [
      { title: "Stokvel created", date: "Jan 2025", completed: true },
      { title: "First contribution cycle", date: "Feb 2025", completed: true },
      { title: "Goal reached", date: "Jan 2028", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 3000, memberCount: 3 },
    ],
    activities: [
      { id: "a11", type: "contribution", text: "Monthly contribution of R 3 000 collected", timestamp: "2 hours ago" },
    ],
  },
  {
    id: "s8",
    name: "Pretoria Family Savers",
    description: "Long-term savings for family goals and generational wealth.",
    goal: "home",
    duration: 60,
    monthlyContribution: 3000,
    maxMembers: 10,
    currentMembers: 9,
    riskAppetite: "conservative",
    privacy: "public",
    createdAt: "2023-03-01",
    members: Array.from({ length: 9 }, (_, i) => ({
      id: `pfs-${i}`,
      name: ["Thabo M.", "Sizwe K.", "Lerato N.", "Nomsa D.", "Jabu S.", "Kgosi P.", "Thembi R.", "Bongani T.", "Zanele M."][i],
      role: i === 4 ? "admin" : "member",
      contributionStatus: i < 7 ? "paid" : "pending",
    })),
    milestones: [
      { title: "Stokvel created", date: "Mar 2023", completed: true },
      { title: "10 members joined", date: "May 2023", completed: true },
      { title: "First contribution cycle", date: "Apr 2023", completed: true },
      { title: "R 500 000 reached", date: "Mar 2025", completed: false },
      { title: "Goal reached", date: "Mar 2028", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 27000, memberCount: 9 },
      { month: "January 2025", amount: 27000, memberCount: 9 },
    ],
    activities: [
      { id: "a12", type: "contribution", text: "Monthly contribution of R 27 000 collected", timestamp: "2 hours ago" },
    ],
  },
  {
    id: "s9",
    name: "Gqeberha Startup Collective",
    description: "Entrepreneurs and innovators building the future of Gqeberha.",
    goal: "business",
    duration: 12,
    monthlyContribution: 1500,
    maxMembers: 6,
    currentMembers: 2,
    riskAppetite: "aggressive",
    privacy: "invite-only",
    createdAt: "2025-02-01",
    members: [
      { id: "u1", name: "Thabo M.", role: "member", contributionStatus: "paid" },
      { id: "gsc-1", name: "Sizwe K.", role: "admin", contributionStatus: "paid" },
    ],
    milestones: [
      { title: "Stokvel created", date: "Feb 2025", completed: true },
      { title: "First contribution cycle", date: "Mar 2025", completed: false },
      { title: "Goal reached", date: "Feb 2026", completed: false },
    ],
    payments: [],
    activities: [
      { id: "a13", type: "member_joined", text: "Thabo M. joined the stokvel", timestamp: "1 week ago" },
    ],
  },
  {
    id: "s10",
    name: "Bloemfontein Custom Crew",
    description: "Saving for farm equipment and agricultural tools.",
    goal: "custom",
    customGoal: "Farm equipment",
    duration: 24,
    monthlyContribution: 2000,
    maxMembers: 8,
    currentMembers: 5,
    riskAppetite: "moderate",
    privacy: "public",
    createdAt: "2024-04-01",
    members: Array.from({ length: 5 }, (_, i) => ({
      id: `bcc-${i}`,
      name: ["Thabo M.", "Sizwe K.", "Lerato N.", "Nomsa D.", "Jabu S."][i],
      role: i === 1 ? "admin" : "member",
      contributionStatus: i < 4 ? "paid" : "pending",
    })),
    milestones: [
      { title: "Stokvel created", date: "Apr 2024", completed: true },
      { title: "First contribution cycle", date: "May 2024", completed: true },
      { title: "Goal reached", date: "Apr 2026", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 10000, memberCount: 5 },
      { month: "January 2025", amount: 10000, memberCount: 5 },
    ],
    activities: [
      { id: "a14", type: "contribution", text: "Monthly contribution of R 10 000 collected", timestamp: "2 hours ago" },
    ],
  },
  {
    id: "s11",
    name: "Polokwane Home Dreamers",
    description: "Working together to achieve home ownership in Polokwane.",
    goal: "home",
    duration: 36,
    monthlyContribution: 1800,
    maxMembers: 12,
    currentMembers: 7,
    riskAppetite: "conservative",
    privacy: "public",
    createdAt: "2024-05-01",
    members: Array.from({ length: 7 }, (_, i) => ({
      id: `phd-${i}`,
      name: ["Thabo M.", "Sizwe K.", "Lerato N.", "Nomsa D.", "Jabu S.", "Kgosi P.", "Thembi R."][i],
      role: i === 2 ? "admin" : "member",
      contributionStatus: i < 5 ? "paid" : "pending",
    })),
    milestones: [
      { title: "Stokvel created", date: "May 2024", completed: true },
      { title: "First contribution cycle", date: "Jun 2024", completed: true },
      { title: "Goal reached", date: "May 2027", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 12600, memberCount: 7 },
      { month: "January 2025", amount: 12600, memberCount: 7 },
    ],
    activities: [
      { id: "a15", type: "contribution", text: "Monthly contribution of R 12 600 collected", timestamp: "2 hours ago" },
    ],
  },
  {
    id: "s12",
    name: "Rustenburg Travel Group",
    description: "Adventure seekers saving for unforgettable journeys.",
    goal: "travel",
    duration: 24,
    monthlyContribution: 2200,
    maxMembers: 10,
    currentMembers: 8,
    riskAppetite: "moderate",
    privacy: "public",
    createdAt: "2024-07-01",
    members: Array.from({ length: 8 }, (_, i) => ({
      id: `rtg-${i}`,
      name: ["Thabo M.", "Sizwe K.", "Lerato N.", "Nomsa D.", "Jabu S.", "Kgosi P.", "Thembi R.", "Bongani T."][i],
      role: i === 5 ? "admin" : "member",
      contributionStatus: i < 6 ? "paid" : "pending",
    })),
    milestones: [
      { title: "Stokvel created", date: "Jul 2024", completed: true },
      { title: "First contribution cycle", date: "Aug 2024", completed: true },
      { title: "Goal reached", date: "Jul 2026", completed: false },
    ],
    payments: [
      { month: "February 2025", amount: 17600, memberCount: 8 },
      { month: "January 2025", amount: 17600, memberCount: 8 },
    ],
    activities: [
      { id: "a16", type: "contribution", text: "Monthly contribution of R 17 600 collected", timestamp: "2 hours ago" },
    ],
  },
];

export const MOCK_ACTIVITIES: DashboardActivity[] = [
  {
    id: "da1",
    type: "contribution",
    text: "You contributed R 1 500 to Thembisa Home Builders",
    subtext: "Payment via FNB •••• 4242",
    timestamp: "2 hours ago",
    stokvelName: "Thembisa Home Builders",
  },
  {
    id: "da2",
    type: "member_joined",
    text: "Sizwe K. joined Luthuli Street Entrepreneurs",
    subtext: "5 of 10 spots filled",
    timestamp: "5 hours ago",
    stokvelName: "Luthuli Street Entrepreneurs",
  },
  {
    id: "da3",
    type: "milestone",
    text: "Maboneng Education Fund reached 50% of its goal",
    subtext: "R 4 800 of R 9 600",
    timestamp: "1 day ago",
    stokvelName: "Maboneng Education Fund",
  },
  {
    id: "da4",
    type: "etf_update",
    text: "Your ETF allocation was updated",
    subtext: "Moderate profile rebalanced",
    timestamp: "2 days ago",
  },
  {
    id: "da5",
    type: "notification",
    text: "Reminder: Your next contribution is due on 1 March",
    subtext: "3 stokvels",
    timestamp: "3 days ago",
  },
];

export const MOCK_CARDS = [
  { id: "c1", bank: "FNB", last4: "4242", expiry: "09/27", isDefault: true },
  { id: "c2", bank: "Capitec", last4: "8888", expiry: "12/26", isDefault: false },
];
